export const GET_PASSMANAGER_DATA_SUCCESS = 'GET_PASSMANAGER_DATA_SUCCESS'
export const GET_PASSMANAGER_DATA_PENDING = 'GET_PASSMANAGER_DATA_PENDING'
export const GET_PASSMANAGER_DATA_ERROR = 'GET_PASSMANAGER_DATA_ERROR'